# Generated by Django 5.1.3 on 2024-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/book/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/book/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/book/images')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
